# Page settings

baseurl = "https://example.org/"
languageCode = "en-us"
title = "Lunar Reflections"
copyright = "© Hugo Theme Doors"
googleAnalytics = "UA-180713165-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "hugo-theme-doors"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
aboutMe = ""


disableRSS = true
disableSitemap = true
disable404 = true

# Site information
[params]
description = ""
metaDescription = "Turn a personal picture into a unqiue and personal pattern."
ogimage = "images/lu_tote.png"

# Project section
[params.projects]

[[params.projects.list]]
  title = ""
  url = "https://www.etsy.com/shop/LunarReflections"
  description = ""
  image = "images/bg_1.png"
  w = "780"
  h = "518"

[[params.projects.list]]
  title = ""
  url = "https://www.etsy.com/shop/LunarReflections"
  description = ""
  image = "images/bg_2.png"
  w = "780"
  h = "518"

  [[params.projects.list]]
  title = ""
  url = "https://www.etsy.com/shop/LunarReflections"
  description = ""
  image = "images/bg_3.png"
  w = "780"
  h = "518"

  [[params.projects.list]]
  title = ""
  url = "https://www.etsy.com/shop/LunarReflections"
  description = ""
  image = "images/bg_4.png"
  w = "780"
  h = "518"

  [[params.projects.list]]
  title = "Unique & Personal Patterns"
  url = "https://www.etsy.com/shop/LunarReflections"
  description = "A picture of your pet can be transformed into a beautiful pattern"
  image = "images/bg_5.png"
  w = "780"
  h = "518"

[[params.projects.list]]
#title = "About Me"
#url = "https://www.etsy.com/shop/LunarReflections"
#description = "I am always experimenting with different ways to express an image. Once while on vacation I took several shots through the center hole of a cheese cracker which turned out to be some of my favorite pictures. Over the last few years I have been trying to take reflection photos that create beautiful abstract designs. My desire was to make organic images without the use of filters or photoshopping effects."
#d2 = "The method I use allows me to create images that are uniquely different every time. I have used many subjects to create my art but some of my favorites have been found through my travels. Things such as Light Houses, Lakes, Sun Sets, Waterfalls, Trains, Bridges and Flowers. I have even started incorporating pictures of family pets into my designs. These unique designs can be used on everything from wall art to tote bags."
#d3 = "I have even begun to explore creating a clothing line as well as creating personalized art for individuals by using the high quality images they send to me. I continue to push my creativity and explore new and exciting new ways to share my art with the world."
#image = "images/about_me.jpg"
#w = "780"
#h = "800"

# Subproject section
# [params.subprojects]
#
# [[params.subprojects.list]]
#   title = "Service 1"
#   url = ""
#   description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
#   image = "images/work2.jpg"
#   w = "780"
#   h = "522"

# Contact section
[params.contact]
description = "I would like to hear from you! Please contact me via my Etsy shop."
etsy = "https://www.etsy.com/shop/LunarReflections"
instagram = "https://www.instagram.com/lunarreflectionsshop/"
twitter = ""
facebook = "https://www.facebook.com/pages/category/Art/Lunar-Reflections-Shop-104781101372713/"
linkedin = ""
github = ""
email = "mailto:lunarreflections@yahoo.com"
