# Page settings

baseurl = "https://example.org/"
languageCode = "en-us"
title = "Lunar Reflections"
copyright = "© Hugo Theme Doors"
googleAnalytics = "UA-xxxxxxxx-x"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "hugo-theme-doors"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disableRSS = true
disableSitemap = true
disable404 = true

# Site information
[params]
description = ""
ogimage = "images/lu_tote.png"

# Project section
[params.projects]

[[params.projects.list]]
title = "Unique & Personal Patterns"
url = ""
description = "A picture of your pet can be transformed into a beautiful pattern"
image = "images/lu_tote.png"
w = "780"
h = "518"

# Subproject section
# [params.subprojects]
#
# [[params.subprojects.list]]
# title = "The work 2"
# url = ""
# description = "Lorem ipsum dolor sit amet"
# image = "images/work2.jpg"
# w = "780"
# h = "522"

# Contact section
[params.contact]
description = "I would like to hear from you. Please contact me via email or social media."
etsy = "https://www.etsy.com/shop/LunarReflections"
instagram = "https://www.instagram.com/lunarreflectionsshop/"
twitter = ""
facebook = "https://www.facebook.com/pages/category/Art/Lunar-Reflections-Shop-104781101372713/"
linkedin = ""
github = ""
email = "lunarreflections@yahoo.com"
